### GET request with a header
GET {{url}}/dogs
Accept: application/json

### GET request with a header
GET {{url}}/dogs/2
Accept: application/json

### GET request with a header
GET {{url}}/dogs/4
Accept: application/json

### POST example
POST {{url}}/dogs
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "name": "Egon",
  "breed": "German Shepard",
  "gender": "Female",
  "age": 10
}

### PUT request
PUT {{url}}/dogs/3
Content-Type: application/json
Accept: application/json

{
  "id": 4,
  "name": "Egon",
  "breed": "Chichuahua",
"gender": "Male",
  "age": 10
}

### DELETE request
DELETE {{url}}/dogs/4


### POST example
POST {{url}}/dogs/doggies
Content-Type: application/json
Accept: application/json

[
{
  "id": 0,
  "name": "Egon",
  "breed": "German Shepard",
  "gender": "Female",
  "age": 10
},
  {
    "id": 0,
    "name": "Ernst",
    "breed": "Poodle",
    "gender": "Female",
    "age": 6
  },
  {
    "id": 0,
    "name": "Fifi",
    "breed": "Dachshund",
    "gender": "Female",
    "age": 8
  },
  {
    "id": 0,
    "name": "Frankie",
    "breed": "Mops",
    "gender": "Male",
    "age": 11
  }
]

### Oliver
GET {{url}}/poems
Accept: application/json
