### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login

{
    "username": "user",
    "password": "test123"
}

> {% client.global.set("jwt_token", response.body.token); %}

###
GET {{url}}/protected/user_demo
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo
Authorization: Bearer {{jwt_token}}
